### ISSUE TITLE
Capacitor values

### ISSUE THREAD

**Issue by stuarteiffert** [danjperron/PIC_MULTI_10_IO#1]
Hi Daniel,

The values aren't listed for all capacitors in the PCB schematic.
C1, C2, and C3 are blank.
From the picture of the assembly all three appear to be 0.1 μF, is this correct?

Also, what voltage did you use for the external power?
Looking at the datasheet for the DC/DC converter cui V7805-500, it expects a nominal voltage of 24V, and the capacitor values seem to depend on this, with the capacitance from Vin to GND being 10μF/50V and Vout to GND being 22μF/10V. 
From the schematic and pictures, it seems that Vin to GND (C6 + C7) = 1.1μF and Vout to GND (C1 + C2+ C3 +C5 +C8) = 1.4μF, which wouldn't make sense for any Vin above 5.5V (unless I've misread something).

Thanks,
Stuart

**Comment by danjperron** [comment]
Well All depends what you need!  


What will be you regulator? What kind of  Power supply you will provide.


In reality capacitor voltage indicate the maximum Voltage . So a 100V will work on 3.3V.


I check All my capacitor and they are all 50V.    



If you are using voltage below 12V use a linear regulator because the Cui is very expensive unless you are using the 5V for R/C servo or you draw too much of it.


I did have a problem with the Xbee and I had to add a 10µF between the gnd and 3.3V. (Too much power oscillation).


This is a picture of two of my test boards . One has a lm7805 and the other Cui DC/DC regulator.





I do have sme with a single 7805 but  I design one with

**Comment by stuarteiffert** [comment]
I was planning on using a 12V DC battery supply (so capacitor sizing on the regulator is not as important) and including some servos, so I went with the Cui for now.

The pictures of your test boards you mentioned aren't visible for me by the way.

Thanks,
Stuart

**Comment by danjperron** [comment]
https://dl.dropboxusercontent.com/s/ybdbr5cnugwys58/multi_IO_using%207805%20or%20Cui%20regulator.jpg

**Comment by danjperron** [comment]
Just in case you didn't know about my google drive doc
https://docs.google.com/document/d/1lXswQlaUgRb-156ZBXZssPgz_-Iv_EBm5P-c_YVQfOA/edit?usp=sharing

The pdf is base on it!

I should put it  in the  readme page

**Comment by stuarteiffert** [comment]
Thanks!
